### ISSUE TITLE
[任务]Using Uniswap V2 Oracle With Storage Proofs

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#103]
- 原文链接：https://medium.com/@epheph/using-uniswap-v2-oracle-with-storage-proofs-3530e699e1d3
- 简要介绍：

---

- Markdown文件： [defi/UniswapV2_Oracle_Storage_Proofs_103.md](https://github.com/lbc-team/Pioneer/blob/master/defi/UniswapV2_Oracle_Storage_Proofs_103.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 57 分
- 校对奖励学分：   分

学分在翻译完成后按中文行数统计 每行译文 1 个学分（不含空行及代码）

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)
> 第一次认领请在认领时加上在登链社区网站上的个人主页地址

**Comment by so349mng** [comment]
认领翻译

**Comment by so349mng** [comment]
已发起PR https://github.com/lbc-team/Pioneer/pull/179
