### ISSUE TITLE
[任务]Solidity Learning: Revert(), Assert(), and Require() in Solidity, and the New REVERT Opcode in the EVM

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#107]
- 原文链接：https://medium.com/blockchannel/the-use-of-revert-assert-and-require-in-solidity-and-the-new-revert-opcode-in-the-evm-1a3a7990e06e
- 简要介绍：

---

- Markdown文件： [eth/Solidity_Learning_107.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Solidity_Learning_107.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 168 分
- 校对奖励学分： 42 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by darrenli6** [comment]
认领翻译
