### ISSUE TITLE
[推荐文章]How to Create NFTs Like NBA Top Shot With Flow and IPFS

### ISSUE THREAD

**Issue by 100miner** [lbc-team/Pioneer#110]
- 原文链接：https://medium.com/pinata/how-to-create-nfts-like-nba-top-shot-with-flow-and-ipfs-701296944bf
- 简要介绍：How to Create NFTs Like NBA Top Shot With Flow and IPFS

> 推荐前最好先搜索确认没有相关中文版本

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/2271
