### ISSUE TITLE
 [任务]Contract_factories_clones

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#12]
Markdown文件： https://github.com/lbc-team/Pioneer/blob/master/eth/Contract_factories_clones.md
内容摘要：How to deploy contracts within contracts as easily and gas-efficient as possible
原文：#3 

预计翻译时间： 3 天
预计校对时间： 1 天
翻译奖励学分： 103 分
校对奖励学分： 26 分

> 回复”认领翻译“ 即可认领翻译任务。
> 关于奖励请参考[规则](https://learnblockchain.cn/article/796)

**Comment by six-days** [comment]
认领翻译
社区id：六天
