### ISSUE TITLE
[任务]How to make smart contracts upgradable!

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#125]
- 原文链接：https://hackernoon.com/how-to-make-smart-contracts-upgradable-2612e771d5a2
- 简要介绍：How to make smart contracts upgradable!

---

- Markdown文件： [eth/contracts_upgradable_125.md](https://github.com/lbc-team/Pioneer/blob/master/eth/contracts_upgradable_125.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分：  分
- 校对奖励学分：  分

学分在翻译完成后按中文行数统计 每行译文 1 个学分（不含空行及代码）

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by passer-byzhang** [comment]
认领翻译

**Comment by passer-byzhang** [comment]
[149](https://github.com/lbc-team/Pioneer/pull/149)
