### ISSUE TITLE
[任务]Uniswap V3 Explained - Concentrated Liquidity, Impermanent Loss, Slippage

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#129]
- 原文链接：https://kushgoyal.com/uniswap-v3-expalined-concentrated-liquidity/
- 简要介绍：

---

- Markdown文件： [defi/Uniswap_V3_Explained_Liquidity_Slippage_129.md](https://github.com/lbc-team/Pioneer/blob/master/defi/Uniswap_V3_Explained_Liquidity_Slippage_129.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分：  60分
- 校对奖励学分：  分

学分在翻译完成后按中文行数统计 每行译文 1 个学分（不含空行及代码）

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)
> 第一次认领请在认领时加上在登链社区网站上的个人主页地址

**Comment by so349mng** [comment]
认领翻译

**Comment by so349mng** [comment]
https://github.com/lbc-team/Pioneer/pull/177

**Comment by so349mng** [comment]
文章

已合并在同一个PR中

**Comment by Nami-upchain** [comment]
@so349mng 麻烦回复一下在社区网站上的ID或者个人主页地址。微信发给晓娜也可以（微信号：upchainedu)

**Comment by so349mng** [comment]
登链账号：songmint

**Comment by so349mng** [comment]
登链账号：songmint
