### ISSUE TITLE
[任务]Using Ethereum’s CREATE2

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#133]
- 原文链接：https://hackernoon.com/using-ethereums-create2-nw2137q7
- 简要介绍：

---

- Markdown文件： [eth/Ethereum_CREATE2_133.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Ethereum_CREATE2_133.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 126 分
- 校对奖励学分： 32 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by xilibi2003** [comment]
@masonhunk 已经认领

**Comment by masonhunk** [comment]
翻译+校对：两周

**Comment by Nami-upchain** [comment]
认领
