### ISSUE TITLE
[推荐文章]How to stream pending transactions with ethers.js

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#134]
- 原文链接：https://www.quicknode.com/guides/defi/how-to-stream-pending-transactions-with-ethers-js
- 简要介绍：

---
- Markdown文件： [eth/stream_pending_transactions_ethers.js_134.md](https://github.com/lbc-team/Pioneer/blob/master/eth/stream_pending_transactions_ethers.js_134.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 120 分
- 校对奖励学分： 29 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by darrenli6** [comment]
认领翻译
