### ISSUE TITLE
[推荐文章]Performing Merkle Airdrop like Uniswap

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#138]
- 原文链接：https://steveng.medium.com/performing-merkle-airdrop-like-uniswap-85e43543a592
- 简要介绍：

---
- Markdown文件： [defi/Performing_Merkle_Airdrop_Uniswap_138.md](https://github.com/lbc-team/Pioneer/blob/master/defi/Performing_Merkle_Airdrop_Uniswap_138.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 每行译文 1 个学分（不含空行及代码）
- 校对奖励学分： 20 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by darrenli6** [comment]
认领翻译

**Comment by EthanOK** [comment]
认领翻译

**Comment by darrenli6** [comment]
https://github.com/lbc-team/Pioneer/pull/155
