### ISSUE TITLE
[任务]Understanding the Value of Uniswap v3 Liquidity Positions

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#139]
- 原文链接：https://lambert-guillaume.medium.com/understanding-the-value-of-uniswap-v3-liquidity-positions-cdaaee127fe7
- 简要介绍：

---
markdown文件：[defi/Understanding_the_Value_of_Uniswap_v3_Liquidity_Positions_139.md](https://github.com/lbc-team/Pioneer/blob/master/defi/Understanding_the_Value_of_Uniswap_v3_Liquidity_Positions_139.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分：  分
- 校对奖励学分：  分

学分在翻译完成后按中文行数统计 每行译文 1 个学分（不含空行及代码）

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)
> 第一次认领请在认领时加上在登链社区网站上的个人主页地址

**Comment by so349mng** [comment]
认领翻译

**Comment by so349mng** [comment]
https://github.com/lbc-team/Pioneer/pull/178

已经PR

**Comment by so349mng** [comment]
登链账号 songmint

**Comment by so349mng** [comment]
请问何时能审核完成发布, 等待翻译下一篇认领的文章.

**Comment by xilibi2003** [comment]
不好意思， 马上审核发布。

你可以继续认领。

**Comment by xilibi2003** [comment]
如果 Issue 列表里，没有适合自己的文章，也可以自己new Issue 来推荐文章， 并自己认领。
