### ISSUE TITLE
[任务]EVM Deep Dives: The Path to Shadowy Super Coder 🥷 💻 - Part 1

### ISSUE THREAD

**Issue by SNWTiny** [lbc-team/Pioneer#141]
- 原文链接：https://noxx.substack.com/p/evm-deep-dives-the-path-to-shadowy
- 简要介绍：

---

- Markdown文件： [eth/EVM_Deep_Dives_Path_Shadowy1_141.md](https://github.com/lbc-team/Pioneer/blob/master/eth/EVM_Deep_Dives_Path_Shadowy1_141.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 171 分
- 校对奖励学分： 42 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by passer-byzhang** [comment]
认领翻译
