### ISSUE TITLE
[任务]How to Create a Solana Token in 5 Steps

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#142]
- 原文链接：https://moralis.io/how-to-create-a-solana-token-in-5-steps/
- 简要介绍：

---

- Markdown文件： [Solana/Create_Solana_Token_5Steps_142.md](https://github.com/lbc-team/Pioneer/blob/master/Solana/Create_Solana_Token_5Steps_142.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 每行译文 1 个学分（不含空行及代码）
- 校对奖励学分：  分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by darrenli6** [comment]
认领翻译

**Comment by EthanOK** [comment]
认领翻译

**Comment by EthanOK** [comment]
#176
