### ISSUE TITLE
[任务]How to use Dapptools

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#152]
- 原文链接：https://medium.com/@patrick.collins_58673/how-to-use-dapptools-code-like-makerdao-fed9909d055b
- 简要介绍：

---

- Markdown文件： [defi/How_to_use_Dapptools_152.md](https://github.com/lbc-team/Pioneer/blob/master/defi/How_to_use_Dapptools_152.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 119 分
- 校对奖励学分： 29 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by EthanOK** [comment]
认领翻译
