### ISSUE TITLE
[任务] Understand EVM Opcodes, Write Better Smart Contracts

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#159]
- 原文链接：https://medium.com/@danielyamagata/understand-evm-opcodes-write-better-smart-contracts-e64f017b619
- 简要介绍：

---
- Markdown文件： [eth/EVM_Opcode159.md](https://github.com/lbc-team/Pioneer/blob/master/eth/EVM_Opcode159.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 76 分
- 校对奖励学分： 19 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by JixiangSoong** [comment]
认领翻译 @Nami-upchain
