### ISSUE TITLE
[任务]Designing an Unbounded List in Solidity 

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#16]
- 原文链接：http://www.blockchainthings.io/article.aspx?i=4
- 简要介绍： 在 Solidity 中设计无限制的列表

---

- Markdown文件： [eth/Designing_Unbounded_List_Solidity.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Designing_Unbounded_List_Solidity.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 125 分
- 校对奖励学分： 31 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by difengJ** [comment]
认领翻译
