### ISSUE TITLE
[任务]Handling NFT Presale — Allowing Lists Off-chain

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#160]
- 原文链接：https://betterprogramming.pub/handling-nft-presale-allow-lists-off-chain-47a3eb466e44
- 简要介绍：

---
- Markdown文件： [NFT/NFT_List_Off_chain160.md](https://github.com/lbc-team/Pioneer/blob/master/NFT/NFT_List_Off_chain160.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 82 分
- 校对奖励学分： 20 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by EthanOK** [comment]
认领翻译

**Comment by EthanOK** [comment]
#165
