### ISSUE TITLE
[任务]Become a blockchain Expert: Beginner to Advanced (for FREE)

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#161]
- 原文链接：https://trustchain.medium.com/become-a-blockchain-expert-beginner-to-advanced-for-free-65ce62606176
- 简要介绍：

---

- Markdown文件： [research/Be_to_Advanced161.md](https://github.com/lbc-team/Pioneer/blob/master/research/Be_to_Advanced161.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 113 分
- 校对奖励学分： 28 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by EthanOK** [comment]
认领翻译

**Comment by EthanOK** [comment]
@Nami-upchain 认领翻译
