### ISSUE TITLE
[任务] secureum 系列文章(八) Ethereum 101

### ISSUE THREAD

**Issue by Nelenum** [lbc-team/Pioneer#173]
- 原文链接：https://secureum.substack.com/p/ethereum-101
- 简要介绍：101 key aspects of Ethereum

---
- Markdown文件： [eth/secureum_Ethereum_101_173.md](https://github.com/lbc-team/Pioneer/blob/master/eth/secureum_Ethereum_101_173.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 325 分
- 校对奖励学分： 81 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)
> 第一次认领请在认领时加上在登链社区网站上的个人主页地址

**Comment by zhangpeizheng123** [comment]
认领翻译

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/5996
