### ISSUE TITLE
[任务]What Is Blockchain Oracle?

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#193]
- 原文链接：https://betterprogramming.pub/what-is-blockchain-oracle-ce2ad4a46c08
- 简要介绍：了解预言机的类型和它们的实际使用案例

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [Oracle/WhatIsBlockchainOracle.md](https://github.com/lbc-team/Pioneer/blob/master/Oracle/WhatIsBlockchainOracle.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 25 分
- 校对奖励学分： 6 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by EthanOK** [comment]
认领翻译
