### ISSUE TITLE
[推荐文章]Common patterns in good NFT contracts

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#194]
- 原文链接：https://www.solidnoob.com/blog/good-nft-contract-patterns
- 简要介绍：分享好的NFT合约中一些最常见的模式

> 推荐前最好先搜索确认没有相关中文版本

**Comment by EthanOK** [comment]
认领翻译

**Comment by xilibi2003** [comment]
这个文章翻译过 https://learnblockchain.cn/article/4339
