### ISSUE TITLE
[任务]Tools for smart contract automation: Guide with examples

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#200]
- 原文链接：https://blog.logrocket.com/tools-smart-contract-automation-guide/
- 简要介绍：

> 推荐前最好先搜索确认没有相关中文版本
---

- Markdown文件： [eth/200_Tools_smart_contract_automation.md](https://github.com/lbc-team/Pioneer/blob/master/eth/200_Tools_smart_contract_automation.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 114 分
- 校对奖励学分： 28 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by EthanOK** [comment]
认领翻译

**Comment by EthanOK** [comment]
#283
