### ISSUE TITLE
[任务]Beginner's Guide to Yul

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#205]
- 原文链接：https://coinsbench.com/beginners-guide-to-yul-12a0a18095ef
- 简要介绍：Yul 入门指南

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [Solana/205_Yul.md](https://github.com/lbc-team/Pioneer/blob/master/Solana/205_Yul.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 103 分
- 校对奖励学分： 25 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by EthanOK** [comment]
认领翻译

**Comment by EthanOK** [comment]
认领翻译

**Comment by Nami-upchain** [comment]
可认领

**Comment by Nami-upchain** [comment]
重新开放认领

**Comment by EthanOK** [comment]
认领翻译
