### ISSUE TITLE
[任务]Why Move? From the Perspective of Programming Language Ecosystem Building

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#207]
- 原文链接：https://rooch.network/blog/why-move-ecosystem
- 简要介绍：从程序语言生态建设讲为什么要用move

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [Solana/207_Why_Move.md](https://github.com/lbc-team/Pioneer/blob/master/Solana/207_Why_Move.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 151 分
- 校对奖励学分： 37 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by liuzel01** [comment]
认领翻译
My profile： 
https://learnblockchain.cn/people/16041

**Comment by xilibi2003** [comment]
有译文： https://learnblockchain.cn/article/6239
