### ISSUE TITLE
[任务]Solving Ethernaut Level 29: Switch

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#215]
- 原文链接：https://blog.softbinator.com/solving-ethernaut-level-29-switch/
- 简要介绍：Solving Ethernaut Level 29: Switch

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [eth/215_Solving_Ethernaut_Level29_Switch.md](https://github.com/lbc-team/Pioneer/blob/master/eth/215_Solving_Ethernaut_Level29_Switch.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 50 分
- 校对奖励学分： 12 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by honey1129** [comment]
认领翻译

**Comment by honey1129** [comment]
pr链接 ：https://github.com/lbc-team/Pioneer/pull/266

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/categories
