### ISSUE TITLE
[任务] Demystifying Digital Identity #1

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#22]
- 原文链接： https://medium.com/3box/demystifying-digital-id-6ec413b129ac
- 简要介绍： 解密数字身份 ID 

---

- Markdown文件： [eth/Digital_Identity_1.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Digital_Identity_1.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 88 分
- 校对奖励学分： 22 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

> 推荐前最好先搜索确认没有相关中文版本

**Comment by peizihui** [comment]
认领翻译
