### ISSUE TITLE
[推荐文章]How To Create a ZK Smart Contract

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#224]
- 原文链接：https://betterprogramming.pub/how-to-create-a-zk-smart-contract-cd948a673749
- 简要介绍：Creating and verifying zero-knowledge proofs in solidity

> 推荐前最好先搜索确认没有相关中文版本

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/5983
