### ISSUE TITLE
[推荐文章] Demystifying Digital Identity part2

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#23]
- 原文链接：https://medium.com/3box/demystifying-digital-identity-2-75dd7dfee2f2
- 简要介绍： 解密数字身份 ID 2 

---
- Markdown文件： [eth/Digital_Identity_2.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Digital_Identity_2.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 76 分
- 校对奖励学分： 19 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)
---

> 推荐前最好先搜索确认没有相关中文版本

**Comment by peizihui** [comment]
认领翻译
