### ISSUE TITLE
[推荐文章]You're writing require statements wrong

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#242]
- 原文链接：https://www.nascent.xyz/idea/youre-writing-require-statements-wrong
- 简要介绍：Don't just write `require` statements for a specific function; write `require` statements for your protocol. `Function Requirements-Effects-Interactions + Protocol Invariants` or the `FREI-PI` pattern can help make your contracts safer by forcing developers to focus on protocol level invariants in addition to function level safety.

> 推荐前最好先搜索确认没有相关中文版本

- Markdown文件： [eth/242_FREI_PI.md](https://github.com/lbc-team/Pioneer/blob/master/eth/242_FREI_PI.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 73 分
- 校对奖励学分： 18 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://github.com/lbc-team/Pioneer/wiki/pioneer)

**Comment by xilibi2003** [comment]
认领

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/6107
