### ISSUE TITLE
[推荐文章]Solidity Coding Standards

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#269]
- 原文链接：https://www.rareskills.io/post/solidity-style-guide
- 简要介绍：The purpose of this article is not to rehash the official [Solidity Style Guide](https://docs.soliditylang.org/en/latest/style-guide.html), which you should read. Rather, it is to document the common deviations from the style guide that come up in code reviews or audits. Some of the items here are not in the style guide, but are common stylistic Solidity developer mistakes.

> 推荐前最好先搜索确认没有相关中文版本

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/6430
