### ISSUE TITLE
[推荐文章]Advanced Wizard Guide to Dune SQL and Ethereum Data Analytics

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#270]
- 原文链接：https://web3datadegens.substack.com/p/advanced-wizard-guide-to-dune-sql
- 简要介绍：In this guide, you’ll learn to navigate Ethereum protocol standards and use advanced SQL functions on call traces, time series balance tracking, dex/nft trades, and ABIs.

> 推荐前最好先搜索确认没有相关中文版本

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/6525
