### ISSUE TITLE
[推荐文章]Basic Wizard Guide to Dune SQL and Ethereum Data Analytics

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#271]
- 原文链接：https://web3datadegens.substack.com/p/a-basic-wizard-guide-to-dune-sql
- 简要介绍：Explaining how Ethereum maps to Dune's tables and giving use case examples for all the basic SQL you need to know to be a data wizard

> 推荐前最好先搜索确认没有相关中文版本

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/6480
