### ISSUE TITLE
[任务]Gas Optimization in Solidity Part I: Variables

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#28]
- 原文链接：https://medium.com/coinmonks/gas-optimization-in-solidity-part-i-variables-9d5775e43dde
- 简要介绍：Gas Optimization in Solidity Part I: Variables

---

- Markdown文件： [eth/Gas_Optimization_1.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Gas_Optimization_1.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 94 分
- 校对奖励学分： 23 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

> 推荐前最好先搜索确认没有相关中文版本

**Comment by difengJ** [comment]
认领
