### ISSUE TITLE
[推荐文章]Zero-Knowledge Proofs Using SnarkJS and Circom

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#291]
- 原文链接：https://betterprogramming.pub/zero-knowledge-proofs-using-snarkjs-and-circom-fac6c4d63202
- 简要介绍：A JavaScript tutorial

> 推荐前最好先搜索确认没有相关中文版本

**Comment by 0xdwong** [comment]
这个 ChinaDeFi 已经翻译过了：https://www.aixinzhijie.com/article/6801530
