### ISSUE TITLE
[任务]Clean Contracts - a guide on smart contract patterns & practices

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#32]
- 原文链接：https://www.wslyvh.com/clean-contracts/
- 简要介绍：Clean Contracts - a guide on smart contract patterns & practices

---
- Markdown文件： [eth/clean_contracts.md](https://github.com/lbc-team/Pioneer/blob/master/eth/clean_contracts.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 154 分
- 校对奖励学分： 38 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by volunteer1024** [comment]
翻译认领

**Comment by volunteer1024** [comment]
翻译认领
