### ISSUE TITLE
[推荐文章] A Hitchhiker's Guide to Solana Program Security

### ISSUE THREAD

**Issue by 0xdwong** [lbc-team/Pioneer#321]
- 原文链接：[https://www.helius.dev/blog/a-hitchhikers-guide-to-solana-program-security](https://www.helius.dev/blog/a-hitchhikers-guide-to-solana-program-security)
- 简要介绍：Solana 程序安全搭便车指南

> 推荐前最好先搜索确认没有相关中文版本

**Comment by 0xdwong** [comment]
认领翻译

**Comment by 0xdwong** [comment]
PR: #322

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/7690
