### ISSUE TITLE
[任务]Best Practices for Smart Contract Development

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#37]
- 原文链接： https://yos.io/2019/11/10/smart-contract-development-best-practices/
- 简要介绍：合约开发最佳实践

> 推荐前最好先搜索确认没有相关中文版本

**Comment by peizihui** [comment]
认领翻译

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/1717
