### ISSUE TITLE
[任务] dynamic-value-arrays-solidity-julian-goddard  

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#39]
- 原文链接：https://www.linkedin.com/pulse/dynamic-value-arrays-solidity-julian-goddard/
- 简要介绍：Solidity 中的动态值数组

> 推荐前最好先搜索确认没有相关中文版本

---
- Markdown文件： [eth/dynamic-value-arrays-solidity.md](https://github.com/lbc-team/Pioneer/blob/master/eth/dynamic-value-arrays-solidity.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 239 分
- 校对奖励学分： 59 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by difengJ** [comment]
认领
