### ISSUE TITLE
[任务]Programming Decentralized Money

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#4]
- 原文链接：https://medium.com/@austin_48503/programming-decentralized-money-300bacec3a4f
- 简要介绍：一个构建 DApp 的新方式（ [scaffold-eth](https://github.com/austintgriffith/scaffold-eth))

- Markdown文件： [eth/Programming_Decentralized_Money.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Programming_Decentralized_Money.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 419 分
- 校对奖励学分： 104 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by Nami-upchain** [comment]
采纳

**Comment by dajuguan** [comment]
认领翻译

**Comment by dajuguan** [comment]
https://github.com/lbc-team/Pioneer/pull/20/
