### ISSUE TITLE
[任务]Using Echidna to test a smart contract library 

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#43]
- 原文链接：https://blog.trailofbits.com/2020/08/17/using-echidna-to-test-a-smart-contract-library/
- 简要介绍：Using Echidna to test a smart contract library
- 优先级：低

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [eth/Echidna-test-contract-library.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Echidna-test-contract-library.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 107 分
- 校对奖励学分： 26 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by darrenli6** [comment]
认领翻译

**Comment by darrenli6** [comment]
https://github.com/lbc-team/Pioneer/pull/144
