### ISSUE TITLE
[推荐文章]Delegation and Voting with EIP-712 Signatures

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#5]
- 原文链接：https://medium.com/compound-finance/delegation-and-voting-with-eip-712-signatures-a636c9dfec5e
- 简要介绍： EIP-712 签名

- Markdown文件： [eth/Delegation_Voting_EIP-712.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Delegation_Voting_EIP-712.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 169 分
- 校对奖励学分： 42 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by difengJ** [comment]
认领
预计5天
