### ISSUE TITLE
[任务] Solidity 0.7 更新点

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#52]
- 原文链接：https://forum.openzeppelin.com/t/changes-in-solidity-0-7-0/3758
- 简要介绍：

> 推荐前最好先搜索确认没有相关中文版本

---

- Markdown文件： [eth/changes-solidity-0.7.0.md](https://github.com/lbc-team/Pioneer/blob/master/eth/changes-solidity-0.7.0.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 85 分
- 校对奖励学分： 21 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by peizihui** [comment]
认领翻译
