### ISSUE TITLE
[任务]Ethereum's Maximum Contract Size Limit is Solved with the Diamond Standard

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#6]
- 原文链接： https://dev.to/mudgen/ethereum-s-maximum-contract-size-limit-is-solved-with-the-diamond-standard-2189
- 简要介绍：委托调用

- Markdown文件： [eth/Diamond_Standard.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Diamond_Standard.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 28 分
- 校对奖励学分： 7 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by Nami-upchain** [comment]
采纳，发布翻译任务

**Comment by peizihui** [comment]
认领翻译

**Comment by peizihui** [comment]
已提交，
https://github.com/peizihui/Pioneer/releases/tag/translation-format
https://github.com/peizihui/Pioneer/blob/master/eth/Diamond_Standard_zh.md 文件
