### ISSUE TITLE
[任务] EIP712 is here: What to expect and how to use it

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#60]
- 原文链接：https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26
- 简要介绍：使用MetaMask 签名 eip712

> 推荐前最好先搜索确认没有相关中文版本
---

- Markdown文件： [eth/EIP712-expect-use.md](https://github.com/lbc-team/Pioneer/blob/master/eth/EIP712-expect-use.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 90 分
- 校对奖励学分： 52 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by Nami-upchain** [comment]
已发布
