### ISSUE TITLE
[推荐文章]The Magic of Digital Signatures on Ethereum

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#64]
- 原文链接：https://medium.com/mycrypto/the-magic-of-digital-signatures-on-ethereum-98fe184dc9c7
- 简要介绍：The Magic of Digital Signatures on Ethereum

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [eth/digital-signature-ethereum.md](https://github.com/lbc-team/Pioneer/blob/master/eth/digital-signature-ethereum.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 214 分
- 校对奖励学分： 53 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by Nami-upchain** [comment]
已有翻译
