### ISSUE TITLE
[任务]How to re-send a transaction with higher gas price using ethers.js

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#68]
- 原文链接：https://www.quiknode.io/guides/web3-sdks/how-to-re-send-a-transaction-with-higher-gas-price-using-ethers-js
- 简要介绍：How to re-send a transaction with higher gas price using ethers.js

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [eth/resend-transaction-ethersjs.md](https://github.com/lbc-team/Pioneer/blob/master/eth/resend-transaction-ethersjs.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 115 分
- 校对奖励学分： 28 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by YashuoKim** [comment]
认领翻译

**Comment by YashuoKim** [comment]
是不是认领了，在5天内完成翻译？
