### ISSUE TITLE
[推荐文章]GasToken: or how I learned to stop worrying and love gas price surges

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#79]
- 原文链接：https://medium.com/coinmonks/gastoken-or-how-i-learned-to-stop-worrying-and-love-gas-price-surges-6aaee9fb0ba3
- 简要介绍：GasToken: or how I learned to stop worrying and love gas price surges

> 推荐前最好先搜索确认没有相关中文版本

**Comment by Nami-upchain** [comment]
https://learnblockchain.cn/article/1707
