### ISSUE TITLE
 [任务]DeFi_Ethereum_USDC_1

### ISSUE THREAD

**Issue by Nami-upchain** [lbc-team/Pioneer#8]
原文链接：https://blog.coinbase.com/introduction-to-building-on-defi-with-ethereum-and-usdc-part-1-ea952295a6e2
Markdown文件： [DeFi_Ethereum_USDC_1.md](https://github.com/lbc-team/Pioneer/blob/master/medium/DeFi_Ethereum_USDC_1.md)

预计翻译时间： 5 天
预计校对时间： 2 天

翻译学分：  分
校对学分：  分

> 翻译及校对学分将在翻译完成后，按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by difengJ** [comment]
认领翻译
备注：大概5天
