### ISSUE TITLE
[任务]Secure Development Recommendations

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#81]
- 原文链接：https://consensys.github.io/smart-contract-best-practices/recommendations/
- 简要介绍：

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [eth/secure-dev-recomm.md](https://github.com/lbc-team/Pioneer/blob/master/eth/secure-dev-recomm.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 532 分
- 校对奖励学分： 133 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by six-days** [comment]
认领

**Comment by xilibi2003** [comment]
https://learnblockchain.cn/article/1890
