### ISSUE TITLE
[推荐文章]A Guide for Developers Interested in Learning Blockchain Development

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#85]
- 原文链接：https://www.linumlabs.com/articles/a-guide-for-developers-interested-in-learning-blockchain-development
- 简要介绍：

> 推荐前最好先搜索确认没有相关中文版本
---
- Markdown文件： [eth/Guide-blockchain-development.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Guide-blockchain-development.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 160 分
- 校对奖励学分： 40 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by man1321859523** [comment]
认领翻译

**Comment by LoAcer** [comment]
认领翻译
