### ISSUE TITLE
[任务]Synthetic Assets in DeFi: Use Cases & Opportunities

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#88]
- 原文链接：https://defiprime.com/synthetic-assets-defi
- 简要介绍：

> 推荐前最好先搜索确认没有相关中文版本

---
- Markdown文件： [eth/Synthetic-Assets-DeFi.md](https://github.com/lbc-team/Pioneer/blob/master/eth/Synthetic-Assets-DeFi.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 100 分
- 校对奖励学分： 25 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by man1321859523** [comment]
打扰，该网址已有该文章的中文版本，请问是否还需要进行翻译工作？[已有相似中文版本](https://www.chainnews.com/articles/109075180253.htm)

**Comment by xilibi2003** [comment]
不用
