### ISSUE TITLE
[任务] Ethereum Merkle Patricia Trie Explained

### ISSUE THREAD

**Issue by xilibi2003** [lbc-team/Pioneer#91]
- 原文链接：https://medium.com/@chiqing/merkle-patricia-trie-explained-ae3ac6a7e123
- 简要介绍：

> 推荐前最好先搜索确认没有相关中文版本
---

- Markdown文件： [eth/eth-merkle-patricia-trie-exp.md](https://github.com/lbc-team/Pioneer/blob/master/eth/eth-merkle-patricia-trie-exp.md)
- 预计翻译时间： 5 天
- 预计校对时间： 3 天
- 翻译奖励学分： 264 分
- 校对奖励学分： 66 分

---
> 回复”认领翻译“ 即可认领翻译任务。
> 翻译及校对学分按行数统计，参考[规则](https://learnblockchain.cn/article/796)

**Comment by yhc166188** [comment]
认领翻译
